// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAWv7adwEj9Cuf8cdekVSz55sbIpu87KBk",
      authDomain: "java-project-638c1.firebaseapp.com",
      projectId: "java-project-638c1",
      storageBucket: "java-project-638c1.appspot.com",
      messagingSenderId: "931098764009",
      appId: "1:931098764009:web:992b022f9a4a49150b8678",
      measurementId: "G-M3VNGCQG22");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyAWv7adwEj9Cuf8cdekVSz55sbIpu87KBk",
      authDomain: "java-project-638c1.firebaseapp.com",
      projectId: "java-project-638c1",
      storageBucket: "java-project-638c1.appspot.com",
      messagingSenderId: "931098764009",
      appId: "1:931098764009:web:992b022f9a4a49150b8678",
      measurementId: "G-M3VNGCQG22");
}
